[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.fileinfo"]

[phases.build]
cmds = ["mkdir -p /app/uploads/cv"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} router.php"
